COMPANION_GENRES = {

    "Alone": {
        "Action":1,
        "Adventure":2,
        "Animation":0,
        "Comedy":1,
        "Crime":2,
        "Documentary":3,
        "Drama":5,
        "Family":0,
        "Fantasy":2,
        "History":3,
        "Horror":2,
        "Music":0,
        "Mystery":5,
        "Romance":1,
        "Science Fiction":4,
        "TV Movie":0,
        "Thriller":4,
        "War":2,
        "Western":0,
        "Foreign":0
    },

    "Friends": {
        "Action":5,
        "Adventure":5,
        "Animation":3,
        "Comedy":5,
        "Crime":4,
        "Documentary":0,
        "Drama":2,
        "Family":2,
        "Fantasy":4,
        "History":1,
        "Horror":3,
        "Music":2,
        "Mystery":2,
        "Romance":2,
        "Science Fiction":4,
        "TV Movie":0,
        "Thriller":3,
        "War":2,
        "Western":1,
        "Foreign":0
    },

    "Family": {
        "Action":2,
        "Adventure":5,
        "Animation":5,
        "Comedy":4,
        "Crime":0,
        "Documentary":1,
        "Drama":2,
        "Family":5,
        "Fantasy":4,
        "History":1,
        "Horror":0,
        "Music":3,
        "Mystery":1,
        "Romance":1,
        "Science Fiction":2,
        "TV Movie":2,
        "Thriller":0,
        "War":0,
        "Western":1,
        "Foreign":1
    },

    "Partner": {
        "Action":2,
        "Adventure":2,
        "Animation":1,
        "Comedy":4,
        "Crime":1,
        "Documentary":1,
        "Drama":5,
        "Family":2,
        "Fantasy":3,
        "History":2,
        "Horror":1,
        "Music":4,
        "Mystery":2,
        "Romance":5,
        "Science Fiction":2,
        "TV Movie":1,
        "Thriller":2,
        "War":1,
        "Western":1,
        "Foreign":2
    },

    "Kids": {
        "Action":2,
        "Adventure":4,
        "Animation":5,
        "Comedy":4,
        "Crime":0,
        "Documentary":1,
        "Drama":1,
        "Family":5,
        "Fantasy":5,
        "History":1,
        "Horror":0,
        "Music":3,
        "Mystery":0,
        "Romance":0,
        "Science Fiction":2,
        "TV Movie":2,
        "Thriller":0,
        "War":0,
        "Western":0,
        "Foreign":1
    }

}